name: Build
on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 19
    - name: clear cache
      run: npm cache clean --force
    - name: confirm node version
      run: node -v
    - name: install dependencies
      run: npm install
    - name: build
      run: npm run package:linux
    - name: upload files
      uses: actions/upload-artifact@v3
      with:
        name: desktop-build 
        path: release/8.0.0

  # build_on_mac:
  #   runs-on: macos-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-node@master
  #     with:
  #       node-version: 16
  #   - name: install dependencies
  #     run: npm install
  #   - name: build
  #     run: npm run package:mac

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 16
    - name: install dependencies
      run: npm install
    - name: build
      run: npm run package:windows
    - name: upload files
      uses: actions/upload-artifact@v3
      with:
        name: desktop-build 
        path: release/8.0.0

